feat(Maybe): Added HaveSomeValue()
NitroDevs/CSharpFunctionalExtensions.FluentAssertions pull request #11
Opened 2022-08-20 22:41 UTC by MrBogomips

I've added the extension `HaveSomeValue()` that simply asserts that maybe holds some value, without requiring to test the value.

2022-08-21 23:22 UTC, KyleMcMaster requested changes
Thanks for the contribution! I have requested a small change and then I will rereview.

2022-08-21 23:22 UTC, KyleMcMaster commented on src/CSharpFunctionalExtensions.FluentAssertions/MaybeExtensions.cs
> +            .FailWith("Expected a value{reason}");
```suggestion
            .FailWith("Expected a value {reason}");
```

Small whitespace formatting suggestion

2022-08-22 06:00 UTC, MrBogomips commented on src/CSharpFunctionalExtensions.FluentAssertions/MaybeExtensions.cs
> +            .FailWith("Expected a value{reason}");
Ok.

2022-08-23 21:30 UTC, KyleMcMaster approved these changes

2022-08-26 20:25 UTC, merged